[package]
name = "bevy_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
inputbot = "0.6"
bevy_rl = "0.15.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
